### PR TITLE
Added Alpha band handling.

### PR DESCRIPTION
**Pull request by avitebskiy**

### CODE REVIEW

**Review by rddesmond — APPROVED** [review]

**Comment by avitebskiy** [comment]
test this please

**Comment by avitebskiy** [comment]
test this please

**Comment by avitebskiy** [comment]
test this please

**Comment by avitebskiy** [comment]
test this please

**Comment by avitebskiy** [comment]
test this please

**Comment by avitebskiy** [comment]
test this please

**Comment by avitebskiy** [comment]
test this please

**Comment by avitebskiy** [comment]
test this please

**Comment by avitebskiy** [comment]
test this please

**Pull request merged**
